[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fefb887f250>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/acbd3fb61fccad3612417a322b259b91/refresh
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fefb887f3a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/acbd3fb61fccad3612417a322b259b91/refresh
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:810 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fefb887f550>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/acbd3fb61fccad3612417a322b259b91/refresh